export const DEFAULT_OIDC_ENDPOINT = "https://oidc.dev.dentity.com/";

export const OIDC_EVENTS = {
  LOGIN_BEGIN: "LOGIN_BEGIN",
  LOGIN_SUCCEED: "LOGIN_SUCCEED",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_BEGIN: "LOGOUT_BEGIN",
  LOGOUT_SUCCEED: "LOGOUT_SUCCEED",
  LOGOUT_FAILED: "LOGOUT_FAILED",
  GET_TOKEN_BEGIN: "GET_TOKEN_BEGIN¸",
  GET_TOKEN_SUCCEED: "GET_TOKEN_SUCCEED",
  GET_TOKEN_FAILED: "GET_TOKEN_FAILED",
  GET_USER_INFO_BEGIN: "GET_USER_INFO_BEGIN",
  GET_USER_INFO_SUCCEED: "GET_USER_INFO_SUCCEED",
  GET_USER_INFO_FAILED: "GET_USER_INFO_FAILED",
} as const;
